name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: 'Semver (eg: v1.2.3)'
        required: true

jobs:
  release:
    if: github.triggering_actor == 'samber'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
        stable: false

    - name: Test
      run: make test

    - name: Build
      run: make all

    - name: List files
      run: tree -Cfi
    - name: Write new go.mod into logs
      run: cat go.mod
    - name: Write new go.sum into logs
      run: cat go.sum

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          bin/headercheck
          bin/headercheck.so
        name: ${{ inputs.semver }}
        tag_name: ${{ inputs.semver }}
